In [31]:
import sklearn.datasets as datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [38]:
data = datasets.load_boston()
data

C:\Users\ASUS\.conda\envs\ML\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing datase

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [40]:
feature = data['data']
feature_names = data['feature_names']

In [41]:
target = data['target']
print(feature.shape, target.shape)
feature

(506, 13) (506,)


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [42]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [43]:
target = target.reshape(-1, 1)
target.shape

(506, 1)

In [44]:
data = np.concatenate((feature, target), axis=1)
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [45]:
X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.2, random_state=2023)

In [46]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(X_train, y_train)

LinearRegression()

In [47]:
linear.coef_

array([[-1.07082424e-01,  3.87223109e-02,  8.92989147e-03,
         2.42299873e+00, -1.64967974e+01,  3.63279393e+00,
        -5.26514360e-03, -1.38747168e+00,  2.50556442e-01,
        -1.05238685e-02, -8.53797921e-01,  7.06616939e-03,
        -5.27035449e-01]])

In [48]:
linear.intercept_

array([35.85864604])

In [49]:
linear.score(X_test, y_test)

0.7927610576409547

In [52]:
print(feature_names.shape, linear.coef_.shape)
print(feature_names, linear.coef_)

(13,) (1, 13)
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT'] [[-1.07082424e-01  3.87223109e-02  8.92989147e-03  2.42299873e+00
  -1.64967974e+01  3.63279393e+00 -5.26514360e-03 -1.38747168e+00
   2.50556442e-01 -1.05238685e-02 -8.53797921e-01  7.06616939e-03
  -5.27035449e-01]]


In [57]:
[*zip(feature_names, linear.coef_.reshape(-1))]

[('CRIM', -0.10708242397163878),
 ('ZN', 0.03872231094193779),
 ('INDUS', 0.00892989146618284),
 ('CHAS', 2.4229987332492664),
 ('NOX', -16.496797375687976),
 ('RM', 3.6327939262663635),
 ('AGE', -0.005265143595285531),
 ('DIS', -1.3874716843958694),
 ('RAD', 0.2505564421908861),
 ('TAX', -0.010523868532813084),
 ('PTRATIO', -0.8537979206822794),
 ('B', 0.007066169394045602),
 ('LSTAT', -0.5270354487576724)]

In [105]:
w = linear.coef_
w = w.reshape(-1)
w.shape

(13,)

In [107]:
feature_names = feature_names.reshape(-1)

In [108]:
y = ''

In [110]:
for i in range(len(w)):
    print(i)
    if i == len(w) - 1:
        y += '{} * {}'.format(w[i], feature_names[i])
        print(y)
    y += '{} * {} + '.format(w[i], feature_names[i])
    ...

0
1
2
3
4
5
6
7
8
9
10
11
12
-0.10708242397163878 * CRIM + 0.03872231094193779 * ZN + 0.00892989146618284 * INDUS + 2.4229987332492664 * CHAS + -16.496797375687976 * NOX + 3.6327939262663635 * RM + -0.005265143595285531 * AGE + -1.3874716843958694 * DIS + 0.2505564421908861 * RAD + -0.010523868532813084 * TAX + -0.8537979206822794 * PTRATIO + 0.007066169394045602 * B + -0.5270354487576724 * LSTAT


In [104]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
b.shape

(5,)

In [111]:
linear.score(X_test, y_test)

0.7927610576409547

In [112]:
X_train.shape

(404, 13)

In [113]:
X_train

array([[3.53700e-02, 3.40000e+01, 6.09000e+00, ..., 1.61000e+01,
        3.95750e+02, 9.50000e+00],
       [5.69175e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.92680e+02, 1.49800e+01],
       [3.41090e-01, 0.00000e+00, 7.38000e+00, ..., 1.96000e+01,
        3.96900e+02, 6.12000e+00],
       ...,
       [9.51363e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        6.68000e+00, 1.87100e+01],
       [8.40540e-01, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.03420e+02, 1.65100e+01],
       [2.54300e-02, 5.50000e+01, 3.78000e+00, ..., 1.76000e+01,
        3.96900e+02, 7.18000e+00]])

In [114]:
ones = np.ones(shape=(len(X_train), 1))

In [115]:
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [136]:
new_X_train = np.concatenate((X_train, ones), axis=1)
new_X_train.shape

(404, 14)

In [119]:
w = [-0.09933343475981973, 0.043081331703853885, -0.013469148782994544, 2.4700571193063086, -1.0470954333665703, 5.595536115047876, -0.010336360466042714, -0.8512767321757164, 0.13953553606691574, -0.008705283106797704, -0.2879001813772919, 0.012841390173222705, -0.4336363003979212]

In [122]:
w = np.array(w).reshape(-1, 1)

In [124]:
w.shape

(13, 1)

In [125]:
w

array([[-0.09933343],
       [ 0.04308133],
       [-0.01346915],
       [ 2.47005712],
       [-1.04709543],
       [ 5.59553612],
       [-0.01033636],
       [-0.85127673],
       [ 0.13953554],
       [-0.00870528],
       [-0.28790018],
       [ 0.01284139],
       [-0.4336363 ]])

In [126]:
print(w)

[[-0.09933343]
 [ 0.04308133]
 [-0.01346915]
 [ 2.47005712]
 [-1.04709543]
 [ 5.59553612]
 [-0.01033636]
 [-0.85127673]
 [ 0.13953554]
 [-0.00870528]
 [-0.28790018]
 [ 0.01284139]
 [-0.4336363 ]]


In [127]:
w

array([[ 0.90066657],
       [ 1.04308133],
       [ 0.98653085],
       [ 3.47005712],
       [-0.04709543],
       [ 6.59553612],
       [ 0.98966364],
       [ 0.14872327],
       [ 1.13953554],
       [ 0.99129472],
       [ 0.71209982],
       [ 1.01284139],
       [ 0.5663637 ]])

In [135]:
c = np.concatenate((w, np.array([1]).reshape(1, -1)), axis=0)
print(c)

[[-0.09933343]
 [ 0.04308133]
 [-0.01346915]
 [ 2.47005712]
 [-1.04709543]
 [ 5.59553612]
 [-0.01033636]
 [-0.85127673]
 [ 0.13953554]
 [-0.00870528]
 [-0.28790018]
 [ 0.01284139]
 [-0.4336363 ]
 [ 1.        ]]


In [137]:
import sklearn.datasets as datasets
boston = datasets.load_boston()
feature = boston['data']
target = boston['target']
feature.shape,target.shape

C:\Users\ASUS\.conda\envs\ML\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing datase

((506, 13), (506,))

In [143]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(feature,target,test_size=0.2,random_state=2023)

In [144]:
#导入线性回归算法模型的工具类
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
linner = LinearRegression()
linner.fit(x_train,y_train)

LinearRegression()

In [145]:
linner.coef_ #返回每一个维度特征的权重系数

array([-1.07082424e-01,  3.87223109e-02,  8.92989147e-03,  2.42299873e+00,
       -1.64967974e+01,  3.63279393e+00, -5.26514360e-03, -1.38747168e+00,
        2.50556442e-01, -1.05238685e-02, -8.53797921e-01,  7.06616939e-03,
       -5.27035449e-01])

In [146]:
linner.intercept_ #截距

35.858646035234585

In [147]:
linner.score(x_test,y_test)

0.7927610576409547

In [149]:
y_test, linner.predict(X_test)

(array([14.2, 15.6, 23.7, 20.4, 23.1, 50. , 23.2, 36. , 17.1, 14.1, 29.6,
        16.8, 16.2, 24.1, 36.2, 20. , 17.4, 20.6, 30.3, 22.6, 37. , 17.3,
        26.6, 30.1, 23.9, 23.8, 32.4, 19.8, 13.8, 13.8, 19.8, 24.1, 31.1,
        19.1, 13.1, 20.1, 17.1, 10.2, 13.3, 20.7, 29.6, 17.8, 43.1, 14.3,
         9.6, 29.4, 25. , 20.7, 21.9, 16. , 20. , 24.7, 50. , 44.8, 17.1,
        22.6, 18.8, 13.1, 20.9, 30.5, 22.2, 19.3, 24.3, 23.8, 27.9, 48.5,
        46. , 23.9, 20.3, 10.5, 20. , 19.1, 24.8, 12. , 13.8, 24.5,  5. ,
        15. , 37.6, 50. , 50. , 18.5, 50. , 19.5, 17.2, 20.8, 16.5, 22.4,
        13.4, 14.1, 21.7, 19.9, 16.7, 23.2, 11.7, 25.3, 11. , 18.9, 14.9,
        23.1, 12.5, 18.2]),
 array([17.88373482, 15.93398605, 27.49745933, 20.036096  , 25.03112457,
        39.47614869, 22.00971887, 35.38601928, 19.48177633, 16.18050399,
        25.36491384, 19.79496777, 20.62140547, 28.859701  , 27.55771923,
        22.97898307, 17.88785525, 19.4352485 , 32.03157898, 18.99694285,
        30.628

In [150]:
x_test @ linner.coef_ + linner.intercept_

array([17.88373482, 15.93398605, 27.49745933, 20.036096  , 25.03112457,
       39.47614869, 22.00971887, 35.38601928, 19.48177633, 16.18050399,
       25.36491384, 19.79496777, 20.62140547, 28.859701  , 27.55771923,
       22.97898307, 17.88785525, 19.4352485 , 32.03157898, 18.99694285,
       30.62829335, 15.99186553, 28.34644493, 25.13762002, 24.90366714,
       23.09816975, 35.4737565 , 22.1564841 ,  0.49878275,  5.71501779,
       18.47667511, 25.92928313, 31.88306099, 16.71120664, 19.75252956,
       20.24863995, 20.25940158,  6.18879595, 15.70878457, 25.29638159,
       24.59137783, 17.63033272, 36.11003453, 14.33966029, 14.90912498,
       30.65248698, 28.89367557, 22.00730805, 15.50911909, 18.35912557,
       18.22084392, 24.84339237, 36.41730174, 37.62281684, 16.86326336,
       24.80330015, 20.19218769, 14.59413707, 21.23204853, 30.11257552,
       23.91228906, 20.47308051, 28.55358845, 25.05087094, 19.64355459,
       40.8070643 , 39.38860253, 27.6417726 , 22.75509823, 12.38

In [151]:
from sklearn.metrics import mean_squared_error as MSE
y_pred = linner.predict(x_test)
MSE(y_test, y_pred)

20.532784235914466