In [11]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [12]:
data_films = pd.read_excel('../datasets/knn_films.xlsx')
shuffle(data_films)
data_films

C:\Users\ASUS\.conda\envs\ML\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


名字  Action Lens  Love Lens  target
0       前任3            4         10    Love
1       西游记           16          2  Action
2       战狼2           18          3  Action
3     失恋33天            2         13    Love
4      宝贝计划            4          2  Comedy
5       捉妖记           10         10  Action
6      乡村爱情            3          4  Comedy
7   阳光的快乐生活            2          3  Comedy
8     后来的你们            2         11    Love
9      大话西游           18          2  Action
10   速度与激情8            3         19    Love
11     一路向北            5         17    Love

In [13]:
dataset = data_films[['Action Lens', 'Love Lens']]
labels = data_films['target']
labels = np.array(labels).reshape(len(dataset), 1)
dataset.shape, labels.shape

((12, 2), (12, 1))

In [14]:
def load_datasets(path='../datasets/knn_films.xlsx'):
    datasets = pd.read_excel(path, encoding='utf8')
    return datasets

def train_test_spilt(datasets, train_size=0.7, random_state=True):
    if random_state:
        datasets = shuffle(datasets)
    train_num = int(len(datasets) * train_size)

    dataSets = np.array(datasets[['Action Lens', 'Love Lens']])
    labels = np.array(datasets['target']).reshape(len(datasets), 1)
    train_set, train_label = dataSets[:train_num, :], labels[:train_num, :]
    test_set, test_label = dataSets[train_num:len(datasets), :], labels[:train_num:len(datasets), :]

    return train_set, train_label, test_set, test_label

In [29]:
# print(train_test_spilt(load_datasets()))
train_set, train_label, test_set, test_label = train_test_spilt((load_datasets()))
print(train_set, train_label, test_set, test_label)

[[10 10]
 [18  3]
 [ 5 17]
 [ 2  3]
 [ 2 11]
 [ 3  4]
 [16  2]
 [ 2 13]] [['Action']
 ['Action']
 ['Love']
 ['Comedy']
 ['Love']
 ['Comedy']
 ['Action']
 ['Love']] [[ 4  2]
 [ 4 10]
 [ 3 19]
 [18  2]] [['Action']]


C:\Users\ASUS\.conda\envs\ML\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [27]:
a = np.array([[1, 1, 1], [2, 3, 4], [5, 1, 3]])
b = np.array([1, 2, 3]).reshape(3 ,1)
c = a + b
print(c)

[[2 2 2]
 [4 5 6]
 [8 4 6]]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
res = mm.fit_transform(c)
print(res)

In [31]:
normalized = mm.fit_transform(train_set)
print(normalized)

[[0.5        0.53333333]
 [1.         0.06666667]
 [0.1875     1.        ]
 [0.         0.06666667]
 [0.         0.6       ]
 [0.0625     0.13333333]
 [0.875      0.        ]
 [0.         0.73333333]]


In [34]:
def feature_preprocessing(datasets, Normalized=True):
    X_pre = None
    if Normalized:
        data_max = np.max(datasets, axis=0)
        data_min = np.min(datasets, axis=0)
        X_pre = (datasets - data_min) / (data_max - data_min)
    else:
        mean = np.mean(datasets, axis=0)
        std = np.std(datasets, axis=0)
        X_pre = (datasets - mean) / std

    return X_pre

In [36]:
feature_preprocessing(train_set)

array([[0.5       , 0.53333333],
       [1.        , 0.06666667],
       [0.1875    , 1.        ],
       [0.        , 0.06666667],
       [0.        , 0.6       ],
       [0.0625    , 0.13333333],
       [0.875     , 0.        ],
       [0.        , 0.73333333]])

In [37]:
a = np.array([[1, 1, 1], [2, 3, 4], [5, 1, 3]])
b = np.array([[1, 2, 3], [2, 1, 3]]).reshape(3 ,1)


ValueError: cannot reshape array of size 6 into shape (3,1)

In [45]:
def calc_dist(a, b):
    dist = []
    for x in b:
        dist.append(np.sum((x - a) ** 2, axis=1) ** 0.5)
    return dist

In [47]:
res = calc_dist(a, b)
res

[array([0.        , 3.74165739, 4.47213595]),
 array([1.73205081, 2.23606798, 3.31662479]),
 array([3.46410162, 1.41421356, 2.82842712])]

In [48]:
res[0]

array([0.        , 3.74165739, 4.47213595])

In [55]:
index = np.argsort(res[2])
index

array([1, 2, 0], dtype=int64)

array([1, 2], dtype=int64)

In [58]:
a = np.random.randint(0, 10, size=(10, 1))
print(a)

[[2]
 [7]
 [5]
 [1]
 [4]
 [2]
 [0]
 [9]
 [6]
 [8]]


In [61]:
print(a.reshape(-1))

[2 7 5 1 4 2 0 9 6 8]


In [64]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [65]:
iris = load_iris()
feature = iris['data']
target = iris['target']
feature.shape,target.shape

((150, 4), (150,))

In [68]:
print(np.array(target))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [72]:
print(np.array(load_datasets()['target']))

['Love' 'Action' 'Action' 'Love' 'Comedy' 'Action' 'Comedy' 'Comedy'
 'Love' 'Action' 'Love' 'Love']


C:\Users\ASUS\.conda\envs\ML\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [73]:
from sklearn.utils import shuffle
datasets = load_iris()

In [74]:
datasets

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [92]:
feature = np.array(datasets['data'])
labels = np.array(datasets['target']).reshape(-1, 1)
feature.shape, labels.shape
res = np.concatenate((feature, labels), axis=1)

In [94]:
res = shuffle(res)
res

array([[6.9, 3.1, 5.4, 2.1, 2. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.5, 3.2, 5.1, 2. , 2. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [5.1, 3.8, 1.9, 0.4, 0. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [6.4, 3.1, 5.5, 1.8, 2. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [6.4, 2.8, 5.6, 2.1, 2. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.9, 3. , 5.1, 1.8, 2. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5. , 3.2, 1.2, 0.2, 0. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [5.5, 2

In [96]:
res[:, -1]

array([2., 2., 2., 0., 0., 1., 1., 0., 2., 1., 2., 1., 0., 0., 0., 2., 2.,
       1., 0., 0., 2., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 2., 1., 2.,
       1., 1., 1., 1., 2., 0., 0., 2., 2., 1., 1., 0., 1., 1., 2., 2., 0.,
       2., 0., 2., 2., 0., 0., 0., 2., 2., 1., 1., 1., 2., 1., 0., 2., 0.,
       2., 2., 1., 2., 0., 0., 0., 1., 1., 1., 0., 2., 2., 1., 1., 0., 0.,
       1., 2., 1., 0., 0., 2., 1., 0., 0., 2., 1., 2., 0., 1., 2., 1., 2.,
       2., 0., 1., 0., 0., 2., 2., 1., 2., 2., 2., 1., 0., 0., 1., 0., 2.,
       1., 1., 2., 0., 1., 2., 0., 2., 2., 0., 0., 2., 1., 1., 2., 0., 2.,
       1., 1., 1., 2., 1., 0., 1., 1., 0., 0., 2., 2., 0., 1.])

In [99]:
datasets = load_iris()
datasets['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [103]:
df = pd.read_csv('../datasets/adults.txt')
df = df[['age','education_num','occupation','hours_per_week','salary']]
df.head(3)

age  education_num         occupation  hours_per_week salary
0   39             13       Adm-clerical              40  <=50K
1   50             13    Exec-managerial              13  <=50K
2   38              9  Handlers-cleaners              40  <=50K

In [135]:
# feature = df[]
col_names = df.columns[df.columns != 'salary']
feature = df[col_names]
labels = df['salary']
feature.shape, labels.shape

((32561, 4), (32561,))

In [136]:
occupation_count = feature['occupation'].unique()
occupation_count

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [137]:
count = 1
occu_dic = {}
for occ in occupation_count:
    occu_dic[occ] = count
    count += 1
occu_dic

{'Adm-clerical': 1,
 'Exec-managerial': 2,
 'Handlers-cleaners': 3,
 'Prof-specialty': 4,
 'Other-service': 5,
 'Sales': 6,
 'Craft-repair': 7,
 'Transport-moving': 8,
 'Farming-fishing': 9,
 'Machine-op-inspct': 10,
 'Tech-support': 11,
 '?': 12,
 'Protective-serv': 13,
 'Armed-Forces': 14,
 'Priv-house-serv': 15}

In [138]:
feature['occupation'] = feature['occupation'].map(occu_dic)
feature

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3028\1879909711.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feature['occupation'] = feature['occupation'].map(occu_dic)


age  education_num  occupation  hours_per_week
0       39             13           1              40
1       50             13           2              13
2       38              9           3              40
3       53              7           3              40
4       28             13           4              40
...    ...            ...         ...             ...
32556   27             12          11              38
32557   40              9          10              40
32558   58              9           1              40
32559   22              9           1              20
32560   52              9           2              40

[32561 rows x 4 columns]

In [139]:
feature = np.array(feature)

In [141]:
print(feature)

[[39 13  1 40]
 [50 13  2 13]
 [38  9  3 40]
 ...
 [58  9  1 40]
 [22  9  1 20]
 [52  9  2 40]]


In [142]:
labels

0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
         ...  
32556    <=50K
32557     >50K
32558    <=50K
32559    <=50K
32560     >50K
Name: salary, Length: 32561, dtype: object

In [145]:
print(np.array(labels).reshape(-1, 1))

[['<=50K']
 ['<=50K']
 ['<=50K']
 ...
 ['<=50K']
 ['<=50K']
 ['>50K']]


In [146]:
datasets = pd.read_csv('../datasets/adults.txt')
shuffle(datasets)
datasets = datasets[['age', 'education_num', 'occupation', 'hours_per_week', 'salary']]

col_names = datasets.columns[datasets.columns != 'salary']
feature = datasets[col_names]
labels = np.array(datasets['salary'])

In [147]:
datasets_oh = pd.get_dummies(feature['occupation'])
datasets_oh

?  Adm-clerical  Armed-Forces  Craft-repair  Exec-managerial  \
0      0             1             0             0                0   
1      0             0             0             0                1   
2      0             0             0             0                0   
3      0             0             0             0                0   
4      0             0             0             0                0   
...   ..           ...           ...           ...              ...   
32556  0             0             0             0                0   
32557  0             0             0             0                0   
32558  0             1             0             0                0   
32559  0             1             0             0                0   
32560  0             0             0             0                1   

       Farming-fishing  Handlers-cleaners  Machine-op-inspct  Other-service  \
0                    0                  0                  0              0   
1                    0                  0                  0              0   
2                    0                  1                  0              0   
3                    0                  1                  0              0   
4                    0                  0                  0              0   
...                ...                ...                ...            ...   
32556                0                  0                  0              0   
32557                0                  0                  1              0   
32558                0                  0                  0              0   
32559                0                  0                  0              0   
32560                0                  0                  0              0   

       Priv-house-serv  Prof-specialty  Protective-serv  Sales  Tech-support  \
0                    0               0                0      0             0   
1                    0               0                0      0             0   
2                    0               0                0      0             0   
3                    0               0                0      0             0   
4                    0               1                0      0             0   
...                ...             ...              ...    ...           ...   
32556                0               0                0      0             1   
32557                0               0                0      0             0   
32558                0               0                0      0             0   
32559                0               0                0      0             0   
32560                0               0                0      0             0   

       Transport-moving  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
32556                 0  
32557                 0  
32558                 0  
32559                 0  
32560                 0  

[32561 rows x 15 columns]

In [148]:
feature = pd.concat((feature, datasets_oh), axis=1).drop(labels='occupation', axis=1)
feature

age  education_num  hours_per_week  ?  Adm-clerical  Armed-Forces  \
0       39             13              40  0             1             0   
1       50             13              13  0             0             0   
2       38              9              40  0             0             0   
3       53              7              40  0             0             0   
4       28             13              40  0             0             0   
...    ...            ...             ... ..           ...           ...   
32556   27             12              38  0             0             0   
32557   40              9              40  0             0             0   
32558   58              9              40  0             1             0   
32559   22              9              20  0             1             0   
32560   52              9              40  0             0             0   

       Craft-repair  Exec-managerial  Farming-fishing  Handlers-cleaners  \
0                 0                0                0                  0   
1                 0                1                0                  0   
2                 0                0                0                  1   
3                 0                0                0                  1   
4                 0                0                0                  0   
...             ...              ...              ...                ...   
32556             0                0                0                  0   
32557             0                0                0                  0   
32558             0                0                0                  0   
32559             0                0                0                  0   
32560             0                1                0                  0   

       Machine-op-inspct  Other-service  Priv-house-serv  Prof-specialty  \
0                      0              0                0               0   
1                      0              0                0               0   
2                      0              0                0               0   
3                      0              0                0               0   
4                      0              0                0               1   
...                  ...            ...              ...             ...   
32556                  0              0                0               0   
32557                  1              0                0               0   
32558                  0              0                0               0   
32559                  0              0                0               0   
32560                  0              0                0               0   

       Protective-serv  Sales  Tech-support  Transport-moving  
0                    0      0             0                 0  
1                    0      0             0                 0  
2                    0      0             0                 0  
3                    0      0             0                 0  
4                    0      0             0                 0  
...                ...    ...           ...               ...  
32556                0      0             1                 0  
32557                0      0             0                 0  
32558                0      0             0                 0  
32559                0      0             0                 0  
32560                0      0             0                 0  

[32561 rows x 18 columns]

In [157]:
with open('../datasets/datingTestSet.txt') as file:
    dataSets_list = []
    for line in file:
        dataSets_list.append(line.strip().split())
dataSets = np.array(dataSets_list)
feature = dataSets[:, :-1].astype(np.float)
labels = np.array(dataSets[:, -1])
labels

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3028\2124304210.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  feature = dataSets[:, :-1].astype(np.float)


array(['largeDoses', 'smallDoses', 'didntLike', 'didntLike', 'didntLike',
       'didntLike', 'largeDoses', 'largeDoses', 'didntLike', 'largeDoses',
       'didntLike', 'didntLike', 'smallDoses', 'didntLike', 'didntLike',
       'didntLike', 'didntLike', 'didntLike', 'smallDoses', 'largeDoses',
       'smallDoses', 'didntLike', 'smallDoses', 'largeDoses',
       'smallDoses', 'largeDoses', 'smallDoses', 'largeDoses',
       'smallDoses', 'didntLike', 'largeDoses', 'didntLike', 'largeDoses',
       'didntLike', 'smallDoses', 'didntLike', 'didntLike', 'smallDoses',
       'largeDoses', 'largeDoses', 'didntLike', 'smallDoses',
       'largeDoses', 'largeDoses', 'largeDoses', 'didntLike', 'didntLike',
       'didntLike', 'didntLike', 'smallDoses', 'smallDoses', 'didntLike',
       'largeDoses', 'smallDoses', 'smallDoses', 'smallDoses',
       'smallDoses', 'largeDoses', 'didntLike', 'smallDoses', 'didntLike',
       'smallDoses', 'smallDoses', 'smallDoses', 'smallDoses',
       'smallDoses